
version: "3.8"
services:
  frontend:
    build:
      context: .
    ports:
      - 5000:5000
    volumes:
      - /app
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
