name: Docker CI/CD

# Workflow will trigger on every push to the main branch
on:
  push:
    branches:
      - main

jobs:
  # Job to build and push Docker image to GitLab
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 1: Docker login to GitLab registry
    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        registry: registry.gitlab.com
        username: ${{ secrets.GITLAB_USERNAME }}
        password: ${{ secrets.GITLAB_PASSWORD }} 

    # Step 2: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver: docker-container

    # Step 3: Build Docker image
    - name: Build Docker image
      run: |
        docker build -t registry.gitlab.com/muhammadumair185/quiz-game:latest .
    
    # Step 4: Push Docker image to GitLab registry
    - name: Push Docker image
      run: |
        docker push registry.gitlab.com/muhammadumair185/quiz-game:latest
